### ISSUE TITLE
Dynamic elements in locators?

### ISSUE THREAD

**Issue by gerrymcgovern1** [boakley/robotframework-pageobjectlibrary#12]
I am testing an application where I have to select different items in a navigation bar. So in my locators I have:
```
"ShoesCategory": "//a[contains(text(),'Shoes')]",
"CoatsCategory": "//a[contains(text(),'Coats')]",

```
and then I have 2 separate methods like this to click 

```
def click_shoes_category(self):
    self.se2lib.click_element(self.locator.ShoesCategory)

def click_coats_category(self):
   self.se2lib.click_element(self.locator.CoatsCategory)
```
I have quite a number of different categories to select and verify, is there a way to DRY this up so that I can pass a variable into the locator? So something like this:

`
     "category": "//a[contains(text(),'[%s]')] % category"`

And then have a method like this:
```
 def click_category(self, category):
     self.se2lib.click_element(self.locator.category)
```

Any help would be great, thanks!

**Comment by boakley** [comment]
You would do it almost exactly how you specified, just move the
substitution to where you actually use the locator

...

"category": "//a[contains(text(),'[%s]')]"

...

 def click_category(self, category):
     self.se2lib.click_element(self.locator.category % category)


when I do this in my own code, I usually name the locator with a suffix
such as "template" or "pattern" (eg: "category_template")

**Comment by gerrymcgovern1** [comment]
Thanks boakley! That worked, although I just had to use  %s rather than [%s]
