### ISSUE TITLE
Need to implement Inheritance using PageObject library 

### ISSUE THREAD

**Issue by shripadoka** [boakley/robotframework-pageobjectlibrary#24]
Need to implement Inheritance using PageObject library where core locators and functions for main page will be in base page and other pages will inherit base page.

Is it possible using this library?

**Comment by boakley** [comment]
Yes, of course it's possible. In fact, inheritance is required, since ultimately your page objects need to inherit from the PageObject base class.

**Comment by shripadoka** [comment]
Will it be possible to provide example? I tried with existing setup but no luck.

**Comment by shripadoka** [comment]
I mean suppose I have my own base class e.g. Fruit class which inherits PageObject base class. Now I want Apple to inherit my base class i.e. Fruit instead of PageObject.

**Comment by boakley** [comment]
I don't understand what you're asking. You inherit like you do for any
other class.

class Apple(Fruit):
    def __init__(self):
        super().__init__()
        ...
    ...
