### ISSUE TITLE
User defined inheritance using Page Object Library

### ISSUE THREAD

**Issue by shripadoka** [boakley/robotframework-pageobjectlibrary#25]
I want to implement my own inheritance using page object library. Want to implement base class inheriting PageObject class  and child class will inherit base class.
e.g. Fruit is my base class which inherits PageObject class and Apple is child class should inherit Fruit class. Tried to implement using PageObject but system throws an error.

**Comment by boakley** [comment]
There's nothing special you need to do. The `PageObject` class is a normal python class. You can inherit from it, and other classes can inherit from any class that inherits from it. If you find that not to be the case, please provide a concrete example that doesn't work the way you expect.
